name="kylian mbappe"
print(name.upper())
print(name.count("m"))
print(name.title())
print(name.capitalize())
print(name.find("e"))
print(name.index("n"))
print(name.isalnum())
print(name.isalpha())
print(name.isdecimal())
print(name.isspace())
print(name.istitle())
print(name.islower())
print(name.isnumeric())
print(name.rfind("a"))
print(name.replace("kylian","cristiano"))